contest3taskA->main
MaximilianYan/CodeReview pull request #3
Opened 2023-04-27 12:39 UTC by MaximilianYan

Тимофеев Максимилиан Борисович Б05-233 1 курс 86549860

2023-04-28 01:12 UTC, VladislavHacker requested changes
молодец, а теперь перепиши пожалуйста все адекватно, чтобы это было похоже на код не "лишь бы прошло тесты"

там функцию для поиска вхождений и т д)

2023-04-28 09:10 UTC, MaximilianYan commented
посылка 86613668

2023-05-18 19:52 UTC, LightVillet approved these changes

2023-05-22 21:48 UTC, VladislavHacker approved these changes

2023-05-22 21:48 UTC, VladislavHacker commented on contest3/A.001.c
> +    scanf("%s %s", s, p);
ну лимиты указывать надо ребят...

2023-05-22 21:48 UTC, merged